import os

POLL_INTERVAL = int(os.environ.get("POLL_INTERVAL"))
SOLARMAN_EMAIL = os.environ.get("SOLARMAN_EMAIL")
SOLARMAN_PASSWORD = os.environ.get("SOLARMAN_PASSWORD")
SOLARMAN_APPSECRET = os.environ.get("SOLARMAN_APPSECRET")
SOLARMAN_APPID = os.environ.get("SOLARMAN_APPID")
SOLARMAN_INVERTER = os.environ.get("SOLARMAN_INVERTER")
LOW_BATTERY_LEVEL = int(os.environ.get("LOW_BATTERY_LEVEL", 40))
MQTT_BROKER_HOST = os.environ.get("MQTT_BROKER_HOST")
MQTT_BROKER_PORT = int(os.environ.get("MQTT_BROKER_PORT", 1883))

assert None not in [
    POLL_INTERVAL,
    SOLARMAN_EMAIL,
    SOLARMAN_PASSWORD,
    SOLARMAN_APPSECRET,
    SOLARMAN_APPID,
    SOLARMAN_INVERTER,
    LOW_BATTERY_LEVEL,
    MQTT_BROKER_HOST
], "Please provide a valid environment configuration"
